name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./astro-migration-site/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./astro-migration-site

      - name: Build Astro website
        run: npm run build
        working-directory: ./astro-migration-site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: dadwritestech/blog
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./astro-migration-site/dist
          cname: www.dad-writes-tech.com